config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eatfit.urls')),
]

eatfit/urls.py
from django.shortcuts import render
from django.urls import path
from django.conf.urls.static import static
from config.settings import STATIC_URL, MEDIA_URL, STATIC_ROOT, MEDIA_ROOT, DEBUG
from . import views

app_name = "eatfit"

urlpatterns = [
    path('', views.home_page_view, name="home"),
    path('batidos', views.batidos_page_view, name="batidos"),
    path('exercicios', views.exercicios_page_view, name="exercicios"),
    path('alimentos', views.alimentos_page_view, name="alimentos"),
    path('conselhos', views.conselhos_page_view, name="conselhos"),
    path('dietas', views.dietas_page_view, name="dietas"),
    path('website', views.website_page_view, name="website"),
    path('quizz', views.quizz_page_view, name="quizz"),
    path('formulario', views.formulario_page_view, name="contactos"),
    path('tabela', views.tabela_page_view, name="tabela"),
    path('comentarios', views.comentarios_page_view, name="comentarios"),
    path('resultados', views.resultados_page_view, name="resultados"),
    path('resultadosQuiz', views.resultadosQuiz_page_view, name="resultadosQuiz"),
    # TABELA
    path('<int:aula_id>', views.aula, name="aula"),
    path('taulas', views.taulas, name="taulas"),
    path('<int:aula_id>/inscrever', views.inscrever, name="inscrever"),
    # LOGIN
    path('login', views.login_page_view, name="login"),
    path('auth/', views.login_view, name="auth"),
    path('logout', views.logout_view, name="logout"),
    # BASE DE DADOS
    path('upload/', views.upload, name='contactos'),
    path('update/<int:eatandfit_id>', views.update_eatandfit, name='update'),
    path('delete/<int:eatandfit_id>', views.delete_eatandfit, name='delete'),
    # SPA
    path("autores", views.autores, name="autores"),
    path("sections/<int:num>", views.section, name="section")

]

if DEBUG:
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

eatfit/forms.py
from django import forms
from .models import BD, Comment


# definir qual modelo será usado para fazer o formulario
class BDCreate(forms.ModelForm):
    class Meta:
        model = BD
        fields = '__all__'


USER_OPINIONS = [
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
]


class CommentForms(forms.Form):
    compreensao = forms.CharField(label='O conteúdo no website é de clara compreensão? 1(pouca) 5(muita):',
                                  widget=forms.RadioSelect(choices=USER_OPINIONS))
    rigor = forms.CharField(label='Como classifica o rigor da página? 1(pouca) 5(muita):',
                            widget=forms.RadioSelect(choices=USER_OPINIONS))
    facilidade_acesso = forms.CharField(
        label='É fácil aceder aos menus da página (multimedia, Informação,..) 1(pouca) 5(muita):',
        widget=forms.RadioSelect(choices=USER_OPINIONS))
    importante = forms.CharField(label='Sobre a informação apresentada, ela foca-se no importante 1(pouca) 5(muita):',
                                 widget=forms.RadioSelect(choices=USER_OPINIONS))
    complexidade = forms.CharField(label='O website está complexo e com multiplas inter-relacões 1(pouca) 5(muita):',
                                   widget=forms.RadioSelect(choices=USER_OPINIONS))
    perguntas_quizz = forms.CharField(label='As perguntas no quizz eram percetiveis? 1(pouca) 5(muita):',
                                      widget=forms.RadioSelect(choices=USER_OPINIONS))
    amplitude = forms.CharField(label='Quão amplo está o website? 1(pouca) 5(muita):',
                                widget=forms.RadioSelect(choices=USER_OPINIONS))
    originalidade = forms.CharField(label='O website está original? 1(pouca) 5(muita):',
                                    widget=forms.RadioSelect(choices=USER_OPINIONS))
    aconselha = forms.CharField(label='Aconselhava o site a outras pessoas? 1(pouca) 5(muita):',
                                widget=forms.RadioSelect(choices=USER_OPINIONS))
    feedback = forms.CharField(
        label='Diga-nos a sua opinião geral sobre o site e se tiver, faça aqui as suas sugestões para poder-mos melhorar',
        widget=forms.Textarea())


FERGUSON = [
    ( "real","Real Madrid"),
    ("chelsea", "Chelsea"),
    ("manu", "Manchester United"),
    ("celtic", "Celtic"),
]

NEDVED = [
    ("ajax", "Ajax"),
    ("chelsea", "Chelsea"),
    ("atleti", "Atlético Madrid"),
    ("juve", "Juventus"),
]

MESSI = [
    ("messi", "Messi"),
    ("zlatan", "Zlatan Ibrahimovic"),
    ("ronaldo", "Cristiano Ronaldo"),
    ("ronaldinho", "Ronaldinho"),
]

SENNA = [
    ("golf", "Golf"),
    ("surf", "Surf"),
    ("f1", "Fórmula 1"),
    ("ténis", "Ténis"),
]

EVORA = [
    ("100", "100m"),
    ("dardo", "Lançamento do dardo"),
    ("triplo", "Triplo Salto"),
    ("maratona", "Maratona"),
]

MARATONA = [
    ("agostinho", "Joaquim Agostinho"),
    ("lopes", "Carlos Lopes"),
    ("mamede", "Fernando Mamede"),
    ("pinto", "António Pinto"),
]

BRACOS = [
    ("lunges", "Lunges"),
    ("prancha", "Prancha"),
    ("fundos", "Fundos"),
    ("curls", "Bicep Curls"),
    ("ups", "Chin-ups"),
]

SUPERALIMENTO = [
    ("spirulina", "Espirulina"),
    ("gengibre", "Gengibre"),
    ("chocolate", "Chocolate"),
    ("goji", "Goji"),
]

SN = [
    ("sim", "Sim"),
    ("nao", "Não"),
]

LESAO = [
    ("gelo", "Gelo"),
    ("quente", "Quente"),
]

class QuizForms(forms.Form):
    pergunta1 = forms.CharField(label='Para perder peso devo ter uma dieta que me proporcione um défice calórico?',
                                  widget=forms.Select(choices=SN))
    pergunta2 = forms.CharField(label='Alex Ferguson foi treinador de que clube?',
                                  widget=forms.RadioSelect(choices=FERGUSON))
    pergunta3 = forms.CharField(label='Em qual destes clubes se destacou Pavel Nedved?',
                                widget=forms.RadioSelect(choices=NEDVED))
    pergunta4 = forms.CharField(label='Qual destes futebolistas ganhou 4 bolas de ouro seguidas?',
                                widget=forms.RadioSelect(choices=MESSI))
    pergunta5 = forms.MultipleChoiceField(label='Destes exercícios, selecione os exercícios de braços?',
                                choices=BRACOS, widget=forms.CheckboxSelectMultiple)
    pergunta6 = forms.CharField(label='Em que modalidade se destacou Ayrton Senna?',
                                widget=forms.RadioSelect(choices=SENNA))
    pergunta7 = forms.CharField(label='Qual o intruso nesta lista?',
                                widget=forms.RadioSelect(choices=SUPERALIMENTO))
    pergunta8 = forms.CharField(label='Em que especialidade de atletismo se destacou Nelson Évora?',
                                widget=forms.RadioSelect(choices=EVORA))
    pergunta9 = forms.CharField(label='O que devemos aplicar quando nos acabámos de lesionar?',
                                widget=forms.Select(choices=LESAO))
    pergunta10 = forms.CharField(label='Quem foi o vencedor da maratona nos Jogos Olímpicos de 1984?',
                                widget=forms.RadioSelect(choices=MARATONA))

eatfit/views.py
from django.shortcuts import render
from .models import BD, CommentForm, Comment, Quizz, QuizForm
from .forms import BDCreate, CommentForms, QuizForms
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from .utils import get_plot, get_pie
from .calculator import solution


# Create your views here.

def home_page_view(request):
    return render(request, 'eatfit/home.html')


def batidos_page_view(request):
    nutricao = {
        "Batido de Chocolate e Menta": ["292 calorias", "25 g de proteína, 12 g de gordura", "32 g de carboidratos"],
        "Batido de Laranja e Baunilha": ["399 calorias, 32 g de proteína, 14 g de gordura, 39 g de carboidratos"],
        "Batido de Coco e Amêndoa": ["405  calorias, 27 g de proteína, 21 g de gordura, 33 g de carboidratos"],
        "Batido de Morango e Banana": [
            "489 calorias, 39 g de proteína, 11 g de gordura, 59 g de carboidratos, 7 g de fibra"],
    }

    ingredientes = {"Batido de Chocolate e Menta": ["1 colher de proteína de chocolate em pó",
                                                    "3/4 chávena de chocolate preto",
                                                    "1 colher de sopa de nozes",
                                                    "2 colheres de sopa de cacau em pó, não adoçado",
                                                    "1 colher de sopa de aparo de cacau", "2 folhas de menta",
                                                    "4 cubos de gelo",
                                                    "¼ copo de água"],
                    "Batido de Laranja e Baunilha": ["1 colher de pó de proteína de baunilha", "1 laranja",
                                                     "¼ casca de laranja", "1 colher de sopa de nozes",
                                                     "2 colheres de sopa de farinha de linhaça", "1 chávena de água",
                                                     "½ chávena de sumo de laranja",
                                                     "3 cubos de gelo"],
                    "Batido de Coco e Amêndoa": ["1 colher de proteína de chocolate em pó",
                                                 "1 colher de sopa de flocos de coco não adoçados",
                                                 "1 chávena de leite de amêndoas de seda, chocolate preto",
                                                 "1 colher de sopa redonda de manteiga de amêndoa",
                                                 "1½ água em chávenas", "3 cubos de gelo"],
                    "Batido de Morango e Banana": ["Água conforme a necessidade",
                                                   "1 chávena de kefir simples e magro",
                                                   "2 colheres de sopa de nozes",
                                                   "1 copo de morangos picados",
                                                   "1 banana", "1 colher de proteína de soro de baunilha"],

                    }
    imagem = {"Batido de Chocolate e Menta": "eatfit/images/batidochoc.png",
              "Batido de Laranja e Baunilha": "eatfit/images/batidolaran.png",
              "Batido de Coco e Amêndoa": "eatfit/images/batidococo.png",
              "Batido de Morango e Banana": "eatfit/images/batidomorango.png"}

    context = {
        'lista_n': nutricao,
        'ingredientes': ingredientes,
        'imagens': imagem
    }
    return render(request, 'eatfit/batidos.html', context)


def exercicios_page_view(request):
    return render(request, 'eatfit/exercicios.html')


def conselhos_page_view(request):
    cons11 = {"GELO": ["Acabou de se lesionar", "A zona magoada está inflamada", "Acabou de fazer exercício"],
              "QUENTE": ["A lesão é antiga", "Os músculos estão tensos", "Antes de fazer exercício"]
              }

    cons12 = {"GELO": "O propósito do gelo é reduzir a inflamação e minimizar o estrago que a lesão pode fazer",
              "QUENTE": "O calor ajuda a circulação e a mobilidade é melhor para a tensão muscular do que para uma lesão propriamente dita"
              }

    cons13 = {"GELO": "eatfit/images/gelo.png",
              "QUENTE": "eatfit/images/calor.png"
              }

    cons3 = ["Suporte muscular", "Remoção de congestionamento do fluxo de fluidos corporais",
             "Ativação do sistema analgésico endogénico", "Corrige problemas de juntas"]

    context = {
        'conselho11': cons11,
        'conselho12': cons12,
        'conselho13': cons13,
        'conselho3': cons3,
    }
    return render(request, 'eatfit/conselhos.html', context)


def dietas_page_view(request):
    perder = {
        "PROTEÍNAS": "A ingestão de proteínas saudáveis é muito importante, estas ajudam a manter a massa muscular e a aumentar a saciedade. ",
        "GORDURAS": "A ingestão de gorduras deve ser moderada e deve escolher fontes de gorduras saudáveis, as gorduras são nutrientes com um valor calórico mais elavdo, pelo que se deve ter cuidado com o que ingere.",
        "HIDRATOS DE CARBONO": "Deve consumir uma porção menor de hidratos de carbono. Normalmente não precisa de excluir estegrupo alimentar na totalidade, convém no entanto ajustar a dose consumida no dia-a-dia. Opte por ingerir hidratos de  carbono completos, pois estes tem uma absorção mais lenta, promovendo uma maior saciedade. Evite os  hidratos de carbono simples que são de absorção mais rápida, não dando tanta saciedade",
        "HIDRATAÇÃO": "Ingira entre 1.5 a 2 litros de água diariamente",
        "LEGUMES E FRUTAS": "Estes são boas fontes de fibra, vitaminas e minerais, são alimentos saudáveis que ajudam a saciar que apresentam níveis calóricos mais baixos, ter atenção no entanto com a fruta, esta é uma fonte de açúcar e por isso devem ser consumidas com alguma moderação",

    }

    ganhar = {
        "ALIMENTOS NUTRITIVOS": "Lá porque queremos ganhar peso não quer dizer que possamos comer tudo aquilo que queiramos. Deve-se manter uma dieta à base de alimentos que não sejam apenas saudáveis mas também nutritivos. Como por exemplo frango, aveia integral, carnes frescas, carboidratos e vegetais.",
        "MACRONUTRIENTES": "Para ganhar peso é importante ingerir quantidades adequadas dos três macronutrientes mais inportantes, são estes os hidratos de carbono, proteínas e gorduras boas. Eles devem estar presentes em todas as refeições do dia.",
        "PROTEÍNAS": "Estas são as responsáveis pela recuperação e desenvolvimento muscular, indispensáveis para quem treina. Estão normalmente presentes em maior quantidade na carne, peixe, ovos e quijo, sendo também possíveis consumir em alimentos de origem vegetal.",
        "GORDURAS": "Ajudam na absorção de vitaminas e fornecem energia, sendo encontradas no azeite, óleo de coco, nozes e amêndoas.",
        "HIDRATAÇÃO": "Manter-se hidratado é também muito importante, pois esta ajuda ao ganho de massa muscular, que apenas acontece se as células tiverem água para aumentar de volume.",

    }

    imagens_perder = {"PROTEÍNAS": "eatfit/images/xixa.png",
                      "GORDURAS": "eatfit/images/manteiga.png",
                      "HIDRATOS DE CARBONO": "eatfit/images/pao.png",
                      "HIDRATAÇÃO": "eatfit/images/agua.png",
                      "LEGUMES E FRUTAS": "eatfit/images/Abacate_e_Cenoura.png"}

    imagens_ganhar = {"ALIMENTOS NUTRITIVOS": "eatfit/images/corgete.png",
                      "MACRONUTRIENTES": "eatfit/images/ovo.png",
                      "PROTEÍNAS": "eatfit/images/peixe.png",
                      "GORDURAS": "eatfit/images/coconut.png",
                      "HIDRATAÇÃO": "eatfit/images/garrafa.png"}

    context = {
        'perder': perder,
        'imagens_perder': imagens_perder,
        'ganhar': ganhar,
        'imagens_ganhar': imagens_ganhar
    }

    return render(request, 'eatfit/dietas.html', context)


def alimentos_page_view(request):
    alimentos = {
        "GOJI": "São antioxidantes, ricas em proteínas, vitaminas e minerais. Fortalecem ainda osistema imunitário, reforçam a flora intestinal, diminuemos níveis de stress e retardam o envelhecimento das células. Podem ser consumidas em forma de passas, adicionadas ao iogurte, saladas, batidos ou como snacks. Mas atenção, não consuma em exagero... 10 a 15 bagas, cinco a seis vezes por semana é suficiente.",
        "SEMENTES DE CHIA": "São muito ricas em ácidos gordos essenciais (ómega-3 e 6), proteína e fibra, bem como vários minerais – cálcio, ferro, fósforo, selénio, potássio e manganésio. Podem ser consumidas em saladas, iogurtes ou com a água que bebe no dia-a-dia. dose diária aconselhável é de 2 colheres de sopa, divididas em pequenas porções nas diferentes refeições.",
        "SPIRULINA": "Esta alga de cor verde possui quantidades relevantes de proteína, vitamina B12, ferro, ómega-6 e antioxidantes como o betacaroteno. A sua propriedade, juntamente com a elevada capacidade antioxidante, fazem da spirulina um importante aliado para os desportistas, sobretudo no pós-treino, auxiliando na recuperação muscular. Semanalmente, a dose recomendada é de uma colher de chá, uma ou duas vezes por semana. Podendo ser adicionada a batidos, sumos, saladas e sopas.",
        "AVEIA": "Rica em fibras solúveis e insolúveis, a aveia promove o bom funcionamento intestinal e ajuda a reduzir os níveis de colesterol. Devido ao seu índice glicémico moderado, que estabiliza os níveis de glicémia e insulina, ajuda na perda de peso. Cálcio, ferro, proteínas, vitaminas do grupo B e E e hidratos de carbono são as grandes mais-valias deste superalimento. As papas de aveia são a sua forma mais comum e é ideal para pequeno-almoço. Pode ainda ser adicionada a iogurtes ou batidos..",

eatfit/templates/eatfit/aula.html
{% extends 'eatfit/base.html' %}

{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static  'eatfit/css/relations.css' %}">
{% endblock %}

{% block content %}
    <h1>{{ Aula.nome }}</h1>
{% endblock %}

{% block resto %}

    <ul>
        <li>Aula dada pelo(a) {{ Aula.professor }}</li>
        <li>Duracao: {{ Aula.duracao }} minutos</li>
    </ul>
    <br>
    <br>
    <br>

    <h2>Alunos</h2>
    <ul>
        {% for aluno in alunos %}
            <li>{{ aluno }}</li>
        {% empty %}
            <li>Sem alunos</li>
        {% endfor %}
    </ul>

    <form action="{% url 'eatfit:inscrever' Aula.id %}" method="POST">
        {% csrf_token %}
        <select name="aluno">
            {% for non_aluno in non_alunos %}
                <option value="{{ non_aluno.id }}">{{ non_aluno }}</option>
            {% endfor %}
        </select>
        <input type="submit">
    </form>

    <a href="{% url 'eatfit:taulas' %}">Voltar à lista de Aulas</a>
{% endblock %}

eatfit/templates/eatfit/autores.html
{% extends 'eatfit/base.html' %}

{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static  'eatfit/css/autores.css' %}">

    <script>
        function showSection(section) {

            fetch(`/sections/${section}`)
                .then(response => response.text())
                .then(text => {
                    console.log(text);
                    document.querySelector('#content').innerHTML = text;
                    if (text.includes("Daniel")) {
                        document.querySelector('#imagem').src = "{% static "eatfit/images/daniel.jpg" %}"
                    }
                    if (text.includes("Elisa")) {
                        document.querySelector('#imagem').src = "{% static "eatfit/images/elisa.jpeg" %}"
                    }
                });
        }

        document.addEventListener('DOMContentLoaded', function () {
            document.querySelectorAll('button').forEach(button => {
                button.onclick = function () {
                    showSection(this.dataset.section);
                };
            });
        });
    </script>
    <script src="{% static  'eatfit/js/hoverMe.js' %}"></script>

{% endblock %}

{% block content %}
    <h1 class="title" style="color: black; margin-left: -45vw; font-size: 10vw">Sobre Nós</h1>
{% endblock %}

{% block resto %}
    <center>
        <figure style="text-align: center">
            <img class="desc" src="{% static  'eatfit/images/EAT__FIT.jpg' %}">
            <h5>Eat & Fit ajudará em todos os aspetos da sua vida ativa (desporto) e alimentar (dietas). BORA LÁ!</h5>
        </figure>
    </center>
    <h2>Estes são os criadores do Eat&Fit</h2>
    <div class="center">
        <button onmouseover="style.color='yellow'" onmouseout="style.color='white'" data-section="1">Daniel</button>
        <button onmouseover="style.color='yellow'" onmouseout="style.color='white'" data-section="2">Elisa</button>
    </div>

    <div id="content">
    </div>
    <img id="imagem">

    <h4>Passa por cima de mim</h4>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

eatfit/templates/eatfit/batidos.html
{% extends 'eatfit/base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static  'eatfit/css/batidos.css' %}">
{% endblock %}
{% block content %}
    <h1 style="color: black; margin-left: -45vw; font-size: 10vw">BATIDOS</h1>
    <p class="descricaoB">Os batidos são bebidas fornecedoras de
        energia.<br>
        Quem se exercita frequentemente precisa
        de repor as<br>
        energias, vitaminas e nutrientes que são
        necessários para<br>
        executar os exercícios com rapidez e
        sucesso.</p>
{% endblock %}
{% block main %}

    <div class="card-group" style="width: 80rem; margin-left: -7vw">
        {% for k,v in ingredientes.items %}
            <div class="card">
                {% for key,image in imagens.items %}
                    {% if key == k %}
                        <img src="{% static  image %}" style="width: 45%; margin-left: 80px" class="card-img-top"
                             alt="...">
                    {% endif %}
                {% endfor %}
                <div class="card-body">
                    <h5 class="card-title">{{ k }}</h5>
                    <p class="card-text">


                        {% for ingrediente in v %}
                            <li style="font-size: 16px">{{ ingrediente }}</li>
                        {% endfor %}

                    <small class="text-muted">
                        {% for chave,texto in lista_n.items %}
                            {% for macro in texto %}
                                {% if chave == k %}
                                    {{ macro }}
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    </small>
                    </p>


                </div>
            </div>

        {% endfor %}


    </div>



{% endblock %}

eatfit/templates/eatfit/comentarios.html
{% extends 'eatfit/base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static  'eatfit/css/contactos.css' %}">
    <style>
        ul li {
            display: inline-block;
        }
    </style>
{% endblock %}

{% block content %}
    <h1 style="color: black; margin-left: -45vw; font-size: 10vw">COMENTÁRIOS</h1>
{% endblock %}

{% block main %}
    <fieldset style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">
        <h1 class="display-3" style="background-color:#000000;color:#FFFF99; text-align: center">A sua opinião</h1>
        <form method='POST' enctype="multipart/form-data">
            {% csrf_token %}

            {{ form }}

            <button type="submit" style="margin-left: 33vw">Submit</button>

            <br><br>
            <br><br>


        </form>

    </fieldset>
{% endblock %}

eatfit/templates/eatfit/contactos.html
{% extends 'eatfit/base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static  'eatfit/css/contactos.css' %}">
    <script src="{% static  'eatfit/js/alert.js' %}"></script>
{% endblock %}

{% block content %}
    <h1 style="color: black; margin-left: -45vw; font-size: 10vw">CONTACTOS</h1>
{% endblock %}

{% block main %}
    <center>
        <fieldset>
            <h1 class="display-3" style="background-color:#000000;color:#FFFF99;">Dados do Utilizador</h1>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                <label for="fname"><b>Nome:</b> </label>
                <input autofocus required type="text" id="fname" name="nome"
                       style="margin-left: 27vw; margin-top: -2vw">
                <br>
                <label for="lname"><b>Apelido:</b> </label>
                <input required type="text" id="lname" name="apelido" style="margin-left: 27vw; margin-top: -2vw">
                <br>
                <label for="phone"><b>Número de telefone:</b> </label>
                <input required type="tel" id="phone" name="telemovel" style="margin-left: 27vw; margin-top: -2vw">
                <br>
                <label for="email"><b>Email:</b> </label>
                <input required multiple type="email" id="email" name="email"
                       style="margin-left: 27vw; margin-top: -2vw">
                <br>
                <label for="nascimento"><b>Data de nascimento:</b> </label>
                <input required type="date" id="nascimento" max="2020-12-31" min="1920-01-01" name="nascimento"
                       style="margin-left: 27vw; margin-top: -2vw">
                <br>

                <button type="submit" class="btn btn-lg btn-warning">Submit</button>
            </form>
        </fieldset>
    </center>

{% endblock %}

eatfit/templates/eatfit/login.html
{% extends 'eatfit/base.html' %}
{% load static %}


{% block main %}
    <h1 style="margin-left: 50vw">Login</h1>
    {% if message %}
        <div style="margin-left: 47vw"> {{ message }} </div>
    {% endif %}
    <div style="background-color: #ddddff; width: 47vw; height:48vw; margin-top: -20vw; margin-left: -15vw"></div>

    <img style="margin-top: -45vw; margin-left: -8vw" src={% static 'eatfit/images/login.png' %}>

    <form action="{% url 'eatfit:auth' %}" method="POST">
        {% csrf_token %}
        <p style="margin-left: 47vw; margin-top: -27vw">Username:</p>
        <input type="text" name="username" placeholder="username" style="margin-left: 54vw; margin-top: -2.7vw"><br>
        <p style="margin-left: 47vw">Password:</p>
        <input type="password" name="password" placeholder="password" style="margin-left: 54vw; margin-top: -2.7vw"><br>
        <input type="submit" value="Login" style="margin-left: 55vw">
    </form>

{% endblock %}

eatfit/templates/eatfit/resultadosQuiz.html
{% extends 'eatfit/base.html' %}
{% load static %}
{% block content %}
    <h1 style="color: black; margin-left: -45vw; font-size: 10vw">RESULTADOS</h1>
{% endblock %}

{% block resto %}
    <h2>Conseguiu {{ pontos }} pontos!</h2>
    {% for linha in perguntas %}
        <ul>
            <li>
                {{ linha }}
            </li>
        </ul>



    {% endfor %}

    <img style="margin-left: 30vw; margin-top: -20vw" src="data:image/png;base64, {{ chart|safe }}">

{% endblock %}

eatfit/templates/eatfit/tabela.html
{% extends 'eatfit/base.html' %}
{% block main %}
    {% for user in lista %}
        <p>
            {{ user.nome }}
            <a href="{% url 'eatfit:update' user.id %}" class="btn btn-success  btn-sm"
               style="float: right; margin-right: 10px">
                Editar
            </a>
            <a href="{% url 'eatfit:delete' user.id %}" class="btn btn-danger  btn-sm"
               style="float: right; margin-right: 10px">
                Eliminar
            </a>
        </p>
    {% endfor %}
    <a href="{% url 'eatfit:logout' %}" class="btn btn-warning btn-sm">Logout</a>
    <a href="{% url 'eatfit:resultados' %}" class="btn btn-primary btn-sm">Resultados dos Comentários</a>
{% endblock %}

eatfit/templates/eatfit/taulas.html
{% extends 'eatfit/base.html' %}

{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static  'eatfit/css/relations.css' %}">
{% endblock %}

{% block content %}
    <h1>Aulas</h1>
{% endblock %}
{% block resto %}

    <ul>
        {% for aula in aulas %}
            <li><a href="{% url 'eatfit:aula' aula.id %}">Aula {{ aula.id }}: {{ aula.nome }} com
                o(a) {{ aula.professor }}. Duração: {{ aula.duracao }} minutos</a></li>
        {% endfor %}
    </ul>

{% endblock %}